// csharp/recipes_dotnet8_angular17/recipes-app/src/app/add-recipe/add-recipe.component.ts
import { Component, ViewChild, ElementRef } from '@angular/core';
import { RecipeService } from '../recipes-catalog/recipe.service';
import { IRecipe } from '../recipes-catalog/recipe.moudle';



@Component({
  selector: 'app-add-recipe',
  templateUrl: './add-recipe.component.html',
  styleUrls: ['./add-recipe.component.css']
})
export class AddRecipeComponent {
  recipe: IRecipe = {
    id: 0,
    name: '',
    instructions: '',
    imagePath: ''
  };

  selectedFile: File | null = null;
  successMessage: string | null = null;

  // Access the file input through the template reference
  @ViewChild('fileInput') fileInput: ElementRef<HTMLInputElement> | undefined;

  constructor(private recipesSvc: RecipeService) {}

  onFileChange(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      this.selectedFile = input.files[0];
    }
  }

  addRecipe() {
    const formData = new FormData();

    formData.append('name', this.recipe.name);
    formData.append('instructions', this.recipe.instructions);
    if (this.selectedFile) {
      formData.append('image', this.selectedFile, this.selectedFile.name);
    }

    this.recipesSvc.addRecipe(formData).subscribe(
      (response) => {
        this.successMessage = 'Recipe added successfully!';
        this.resetForm(); // Reset form after success
        this.recipesSvc.notifyRecipeAdded();
      },
      (error) => {
        console.error('Error adding recipe:', error);
        this.successMessage = 'Failed to add recipe';
      }
    );
    
  }

  resetForm() {
    // Reset recipe data and selected file
    this.recipe = {
      id: 0,
      name: '',
      instructions: '',
      imagePath: ''
    };
    this.selectedFile = null;

    // Reset the file input field by setting its value to an empty string
    if (this.fileInput) {
      this.fileInput.nativeElement.value = ''; // Clear the file input
    }
  }
}

<div class="container">  
    <!-- Title indicating the component's purpose -->
    <h2 class="component-title">Add a New Recipe</h2> <!-- Add a title for the component -->
      
    <div>
        <input type="text" [(ngModel)]="recipe.name" placeholder="Recipe Name" />        
    </div>
    <div>    
        <editor apiKey="550vhfqch7fpacmeflpv0sj0lcsm4j7zlensn17omo6824yb"
        [(ngModel)]="recipe.instructions"
        [init]="{            
            height: 500,
            menubar: false,
            plugins: 'link image code',
            toolbar: 'undo redo | formatselect | bold italic | alignleft aligncenter alignright | code'
        }"
        ></editor>
    </div>
    <div>
        <input type="file" (change)="onFileChange($event)" accept="image/*" #fileInput />
    </div>
    <div>
        <input type="button" (click)="addRecipe()" value="Add Recipe" />
    </div>

    <!-- Success message display -->
    <div *ngIf="successMessage" class="success-message">{{ successMessage }}</div>
    

</div>

// nodejs/nodejs_react_recipes/recipes-app/src/pages/components/AddRecipe.jsx
import React, { useState } from "react";
import { Editor } from "@tinymce/tinymce-react";
import PropTypes from "prop-types";
import "./AddRecipe.css?no-inline";

function AddRecipe({ onRecipeAdded }) {
  const TINYMCE_APIKEY = "1y2txrzbb9yi55y9qsftdxekakkmjtlot9u3oa7wuilnapdx";
  const [recipe, setRecipe] = useState({ name: "", instructions: "", image: null });
  const [successMessage, setSuccessMessage] = useState("");

  const handleInputChange = (event) => {
    const { name, value } = event.target;
    setRecipe({ ...recipe, [name]: value });
  };

  const handleEditorChange = (content) => {
    setRecipe({ ...recipe, instructions: content });
  };

  const handleFileChange = (event) => {
    const file = event.target.files[0];
    setRecipe({ ...recipe, image: file });
  };

  const addRecipe = async () => {
    const formData = new FormData();
    formData.append("name", recipe.name);
    formData.append("instructions", recipe.instructions);
    if (recipe.image) {
      formData.append("image", recipe.image);
    }

    try {
      const response = await fetch("/api/addRecipe", {
        method: "POST",
        body: formData,
      });
      if (response.ok) {
        setSuccessMessage("Recipe added successfully!");
        setRecipe({ name: "", instructions: "", image: null }); // Reset form
        onRecipeAdded(); // Notify parent to refresh recipes
      } else {
        throw new Error("Failed to add recipe");
      }
    } catch (error) {
      console.error(error);
      setSuccessMessage("Error adding recipe");
    }
  };

  return (
    <div className="addrecipe-container">
      <h2 className="addrecipe-component-title">Add a New Recipe</h2>

      {/* Recipe Name Input */}
      <div>
        <input
          type="text"
          name="name"
          value={recipe.name}
          onChange={handleInputChange}
          placeholder="Recipe Name"
        />
      </div>

      {/* Rich Text Editor for Instructions */}
      <div>
        <Editor
          apiKey={TINYMCE_APIKEY}
          tinymceScriptSrc={`/tinymceCdn/1/${TINYMCE_APIKEY}/tinymce/6/tinymce.min.js`} //"/tinymceCdn"
          value={recipe.instructions}
          init={{
            height: 500,
            menubar: false,
            plugins: "link image code",
            inline: false,
            toolbar:
              "undo redo | formatselect | bold italic | alignleft aligncenter alignright | code",
          }}
          onEditorChange={handleEditorChange}
        />
      </div>

      {/* File Upload Input */}
      <div>
        <input
          type="file"
          onChange={handleFileChange}
          accept="image/*"
        />
      </div>

      {/* Submit Button */}
      <div>
        <button className="addrecipe-button" onClick={addRecipe}>Add Recipe</button>
      </div>

      {/* Success Message */}
      {successMessage && <div className="addrecipe-success-message">{successMessage}</div>}
    </div>
  );
}

AddRecipe.propTypes = {
    onRecipeAdded: PropTypes.func.isRequired,
};
  
export default AddRecipe;
